---
layout: post
title: "A Software Quality Model"
date: 2020-03-01
categories: [quality, model]
---

As explained link:../../../2020/02/09/the-problem-with-software-quality.html[before] quality is subjective. That's why a definition of Software Quality must be quite abstract to be widely acceptable. My favorite definition is an extension of <<DeJ2016,Juran's>> "fitness for use" (<<DeJ2016>>) and maps to the one in the book https://pragprog.com/book/rjnsd/the-nature-of-software-development[The Nature of Software Development] (<<Jef2015>>):

Software Quality is the combination of:

image::/images/post-images/software-quality-definition.svg[align="center"]

Fitness for use is relevant for the end-user and fitness for operation for the operations teams. They are external views and match the <<Jef2015,Jeffries's>> term well-tested. Fitness for change is the internal view of the organization maintaining the system and corresponds to the <<Jef2015,Jeffries's>> term well-designed.

Those three fitnesses need to be balanced, but the definition is too high-level to be useful. To make it more tangible I suggest to link the relevant link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[quality attributes] of the system [to be] defined by the software architect to the three fitnesses.

image::/images/post-images/software-quality-model.svg[align="center"]

While the link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[quality attributes] might still be too abstract, they are linked to concrete quality attribute scenarios.

image::/images/post-images/software-quality-model-with-scenarios.svg[align="center"]

When planning changes of the system the model helps to keep the quality of the system in balance and even allows to adjust the balance when circumstances change.

Revisiting my link:../../../2020/02/09/the-problem-with-software-quality.html[Software Quality definition criteria] the suggested definition & model:

- are _simple_: because the number of elements to consider is managable
- work _intuitively_: stakeholders (e.g. developers) can represent their interests (e.g. fitness for change) while everybody keeps the overview to make conscious decisions
- and are _flexible_: linking the system specific link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[quality attributes] tailors the model to the system context

[bibliography]
== References

- [[[DeJ2016]]]: https://www.amazon.com/Jurans-Quality-Handbook-Performance-Excellence-ebook-dp-B01MEC22PW/dp/B01MEC22PW[Juran's Quality Control Handbook] by Joseph A. DeFeo & Joseph M. Juran
- [[[Jef2015]]]: https://pragprog.com/book/rjnsd/the-nature-of-software-development[The Nature of Software Development] by Ron Jeffries